server:
  forward-headers-strategy: native

app:
  cors:
    allowed-origins:
      - https://red-dawn-raid.castello.ovh

spring:
  profiles:
    active: prod
  jpa:
    hibernate:
      ddl-auto: validate  # en prod, id√©alement "validate"
logging:
  level:
    org.hibernate.SQL: warn
